<html >

<head>
<meta http-equiv="Content-Type" content="text/html; charset=cp1251" />
<link href="css/cabinet_nav.css" rel="stylesheet">
</head>

<body  bgcolor="#92978c" style="font-family:Helvetica, sans-serif;">
    <div class="main-content-wrapper">
        <header class="header-area clearfix">
            <nav class="my-nav">
				<ul>
					
						<div class="catagories-menu">
							<ul>
                                    <li><a href="cabinet.phtml?type=1">Ваш аккаунт</a>
                                    <li><a href="cabinet.phtml?type=2">Заказы</a>
                                    <li><a href="cabinet.phtml?type=3">Подписка на новости</a>
                                    <li><a href="exit.phtml">Выход</a>
							</ul>
						</div>
					
				</ul>       
            </nav>

         
        </header>
    </div>

</body>
</html>								