<html >
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=cp1251" />
        <link href="css/footer.css" rel="stylesheet">
        <script src="https://kit.fontawesome.com/9ebb82abd8.js" crossorigin="anonymous"></script>
    </head>

    <footer class="myfooter">
        <div class="footer-right">
            <a href="https://wapp.click/79874162330"><i class="fab fa-whatsapp"> </i></a>
            <a href="https://www.instagram.com/sens.a.t/"><i class="fab fa-instagram"></i></a>
            <a href="https://t.me/greentess"><i class="fas fa-paper-plane"></i></a>
        </div>

        <div class="footer-left">
            <p class="footer-links" > 
                <a class="link-1" href="glavnaya.phtml">• ГЛАВНАЯ</a> 
                <a href="catalog.phtml?type=3">• КАТАЛОГ</a> 
                <a href="#">• КОНТАКТЫ</a> 
                <a href="cabinet.phtml?type=1">• ЛИЧНЫЙ КАБИНЕТ</a> 
                <a href="basket.phtml">• КОРЗИНА</a> 
            </p>
            <p>CERAMIC vibes &copy; 2022</p>
        </div>

    </footer>
</html>
