<?include("shapka.phtml");?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=cp1251" />
        <link href="css/glavnaya.css" rel="stylesheet">
        <link href="css/shapka.css" rel="stylesheet">
    </head>
    
    <body  bgcolor="#eceae6" style="font-family:Helvetica, sans-serif;">
        <table> 
            <tr> 
                <td>   
                    <div class="mainpicture">  
                        <img src="картинки/фото2.png" width="59%"  > 
                            <font  face="Helvetica"> <p class="textmainpicture1" style = "letter-spacing: 2px;">КЕРАМИКА РУЧНОЙ РАБОТЫ | CERAMIC VIBES</p></font>  
                            <pre><font face="helvetica"><p class="textmainpicture2">JUST LIKE HUMAN<br>       NATURE INTENDED </p></font> </pre> 
                    </div>    
                </td> 
            </tr> 
        </table> 

        <table > 
            <tr> 
                <td height="200px" colspan="2" > 
                <font class="text12"  color=221C1C>ПОЧЕМУ КЕРАМИКА ВАС ЗАИНТЕРЕСУЕТ?? 
                </td> 
            </tr> 
        </table> 
        
        <table> 
            <tr> 
                <td > 
                    <p class="text1" style = "letter-spacing: 3px; padding-left: 11%;"> 
                    НАПОЛНИТЕ СВОЙ ДОМ ТЕПЛОМ<br></p></font>  
                        <p  class="text2" style = "margin-left: 11%;">  
                        Мы  в  абсолютной  ответственности за то, кем являемся, <br>
                        как себя чувствуем, как думаем и как относимся к окружающему нас миру. <br>
                        Остальное - личный выбор. <b>Наш выбор </b> - это не соглашаться ни на что меньшее, <br>
                        чем чувствовать себя спокойными, счастливыми и влюбленными в жизнь, мир, людей вокруг и себя.<br>
                        <br><br>
                        Керамическая посуда отличается особой "тактильной" красотой, <br>
                        рукотворные предметы  несут в  себе частицу  души,  которую  вкладывают <br>
                        в них мастера, и наполняют дом особым, неповторимым теплом спокойствия и любви.<br> </font>
                    </p> 
                    <a href="catalog.phtml?type=3"><input class="btn" type="submit"  value="Перейти к покупкам"  style="margin-left: 11%;">  </a>
                </td> 
                <td >   
                    <img src="картинки/11.jpg" width="80%"  align="left" style="margin-left: 7%;box-shadow: 1vw 1vw 0 0 rgb(168, 157, 147);"> 
                </td> 
            </tr> 
            <tr> 
                <td class="col3" align="middle"  height="100px"  colspan="2"> </td> 
            </tr> 
            <tr> 
                <td> 
                <img src="картинки/история (2).jpg" align="right"  width="75%" style="margin-right:7%; box-shadow: -1vw 1vw 0 0 rgb(168, 157, 147);"> 
                </td> 
                <td > 
                    <p  class="text1" style = "letter-spacing: 3px; margin-left:7%;"> 
                    ПОЧУВСТВУЙТЕ ТВОРЧЕСКОЕ ВЗАИМОДЕЙСТВИЕ</p>  
                        <p class="text2" style = "margin-left:7%;">  
                        Когда посуда ручной работы появляется дома, кухня оживает. <br>
                        Это происходит потому, что такая посуда имеет свой <b>характер</b>. <br>
                        И этот характер складывается из того, что автор вкладывает в свою работу - <br>
                        выбирает особенные материалы, цветовые решения, глазурные сочетания, форму изделий; <br>
                        и того, как сами материалы поведут себя в процессе обработки и  взаимодействуя друг с другом -<br>
                        где-то немного деформируются, где-то проступят крапинки, где-то появятся еле заметные трещинки <br>
                        <br>
                        <br>
                        А на посуде, у которой есть характер, и вам захочется проявить свой характер. <br>
                        Приготовить что-нибудь необычное, красиво сервировать, накрыть празднично <br>
                        стол даже если нет праздника. Как вам такое творческое взаимодействие? <br> 
                         
                    </p> 
                    <a href="catalog.phtml?type=3"><input class="btn" type="submit"  value="Перейти к покупкам"  style="  margin-left: 7%;  ">  </a>
                </td> 
            </tr> 
            <tr> 
                <td  align="middle"  height="150px"  colspan="2"> </td> 
            </tr> 
        <tr> 
            <td  align="center"  height="200px"  colspan="2"> 
                <p class="text1" style = "letter-spacing: 3px;"> 
                    НАША МИССИЯ
                </p> 
                <p  class="text2"> 
                Наша студия керамики отдает предпочтение лаконичным формам, светлым тонам, матовым и <br>
                    шероховатым текстурам. Мы чаще всего не стремимся показать конкретный образ через свою керамику, <br>
                    важнее всего -  настроение, которое можно передать. <br>
                    <br>
                    Приятно осознавать, что наша керамика входит в чей-то дом, <br>
                    становится маленькой, но приятной деталью  повседневной жизни, <br>
                    а может и частью семейной истории.<br>
                </p> 
                  
            </td> 
        </tr> 
            <tr> 
                <td colspan="2"> 
                <img src="картинки/ф.jpg" width="55%" align="left" style="margin-left:23%;"> 
                </td> 
            </tr> 
        </table> 

        <table> 

            <tr> 
                <td  align="middle"  height="50px" > </td> 
            </tr> 
            <tr> 
                <td style="padding-left: 32vw; "> 
                    <form class="frm" action=callback.phtml method=post > 
                        <br>  
                        <p  style = "letter-spacing: 0.145vw; margin-left:25%; font-size: 1.5vw;"> 
                        Форма обратной связи</p>  
                        <p  style = "margin-left:7%; font-size: 0.75vw;"> 
                        Остались вопросы? Заполните форму обратной связи, и в скором времени наш менеджер обязательно с вами свяжется!</p>  
                        <br><br><br> 
                        <label for="name" style="font-size: 0.9vw; padding-left: 3.5vw; ">  Ваше имя:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </label> 
                        <input type="text" id="name" name="name" style=" font-size: 1.2vw; width: 21vw;padding-top: 1vw; padding-bottom: 1vw; border: #ffffff;"> 
                        <br> 
                        <br> 
                        <br> 
                        <label for="phone" style="font-size: 0.9vw;padding-left: 3.5vw;">Ваш телефон:&nbsp;&nbsp;</label> 
                        <input type="text" id="phone" name="phone" style=" font-size: 1.2vw; width: 21vw;padding-top: 1vw; padding-bottom: 1vw; border: #ffffff;"> 
                        <br> 
                        <br> 
                        <br> 
                        <br> 
                        <br> 
                        <input class="btn2" type="submit"  value="Отправить" >  
                        <br> 
                        <br> 
                        <br> 
                    </form> 
                </td> 
            </tr> 
            <tr> 
                <td  align="middle"  height="100px" > </td> 
            </tr> 
        </table> 
    </body>
    <?include("footer.phtml");?>
</html>


