<html>

<head>
 <link href="css/admin_footer.css" rel="stylesheet">
 <script src="https://kit.fontawesome.com/9ebb82abd8.js" crossorigin="anonymous"></script>
</head>

<footer class="myfooter">
 <div class="footer-left">
  <p class="footer-links">
   <a class="link-1" href="admin_index.phtml?type=0">Главная</a>
   <a href="exit.phtml">Выход</a>
  </p>
  <p>CERAMIC vibes &copy; 2022</p>
 </div>

</footer>

</html>

