<?$start=session_start();
$log=$_SESSION["log"];
if(!isset($log)){include("authorization.phtml");} else{
    $items_cats_themes=$_SESSION["items_cats_themes"];
    if($items_cats_themes!=2){?>Ошибка! У вас нет доступа к удалению товаров.<?} else{

include("admin_header.phtml");
?>
<?include("connect.phtml");?>
<html>
    <head>
        <link href="css/new_item.css" rel="stylesheet">
        <link href="css/del_item1.css" rel="stylesheet">
    </head>

    <?
        $id_item=$_GET["id_item"];
        $key=$_POST["key"]; 
    ?>
    

        
        <?if ($key==1)    {?>
                <?
                    $strSQL="SELECT * FROM items  WHERE id_item='".$id_item."'";
                    $result=mysqli_query($connection, $strSQL)or die("Не могу выполнить запрос!");  
                    if($row=mysqli_fetch_array($result))
                    {
                                $strSQL1="DELETE FROM items WHERE id_item=".$id_item;			
                                $result1=mysqli_query($connection, $strSQL1) or die("Не могу выполнить запрос!");	               
                                $message="<div style='width:100%;height:75%; background-color:white;'><div class='subdiv'><div class='subtitle2'><b>Товар был успешно удален.</b></div><br> <div class='aftermes1'><a href='admin_index.phtml?type=3'>Вернуться к списку товаров</a> </div></div></div>";
                                print $message;	
                    }

                ?>  
        <?}
        else{?>
                <form class="my-form" action=del_item.phtml?id_item=<?print $id_item;?> method=post>
            <div style='width:100%;height:75%; background-color:white;'>
            <input class="button" type="submit" value="Да,удалить">
            <br>
            <br>
            <br>
            <br>
                <div class='subdiv'>
                    <div class='aftermes'>
                        <a href='admin_index.phtml?type=3'>Нет, хочу вернуться к списку товаров</a> 
                    </div>
                </div>
            </div>
            <input type=hidden  name=key value=1>
        </form>
        <?}

include("admin_footer.phtml");
?>
<?}?>
<?}?>
