<?$start=session_start();
$log=$_SESSION["log"];
if(!isset($log)){include("authorization.phtml");} else{
    $admins=$_SESSION["admins"];
    if($admins!=2){?>Ошибка! У вас нет доступа к изменению информации о сотруднике.<?} else{


include("admin_header.phtml");
include("connect.phtml");?>
<html>
<head>
<link href="css/edit_cat_theme.css" rel="stylesheet">
<link href="css/info_admin.css" rel="stylesheet">
</head>


<?
$id_admin = $_GET["id_admin"];

$card = $_GET["card"];
$dostup = $_GET["dostup"];

$mykey=$_POST["mykey"];
$im=$_POST["im"];
$fam=$_POST["fam"];
$otch=$_POST["otch"];
$position=$_POST["position"];
$birthday=$_POST["birthday"];
$phone=$_POST["phone"];
$mail=$_POST["mail"];
$login=$_POST["login"];
$pass=$_POST["pass"];

$orders=$_POST["mode"];
$items_cats_themes=$_POST["mode1"];
$callbacks=$_POST["mode2"];
$customers=$_POST["mode3"];
$admins=$_POST["mode4"];

    include("admin_cabinet_nav.phtml");   
?>

        <?
if ($card==1)
    {
            $strSQL="SELECT * FROM admins  WHERE id_admin='".$id_admin."'";
            $result=mysqli_query($connection, $strSQL)or die("Не могу выполнить запрос!"); 
            if($row=mysqli_fetch_array($result))
            {
                if ($mykey==1){
                    if($login!=""&$pass!="")
                    {
                        $strSQL1="UPDATE admins SET im='".$im."',fam='".$fam."',otch='".$otch."',position='".$position."',birthday='".$birthday."',phone='".$phone."',mail='".$mail."',login='".$login."',pass='".$pass."'  WHERE id_admin=".$id_admin;			
                        $result1=mysqli_query($connection, $strSQL1) or die("Не могу выполнить запрос!");	               
                        $message="<div class='mes2'><b>Изменение данных выполнено успешно!</b> </div>";                 
                    }
                    else
                        $message="<div class='mes'><b>Логин и пароль нельзя оставить пустыми!</b> </div>"; 
                }
                    
            print $message;	
            }
        ?>


        <form class="my-form" action=edit_admin.phtml?card=1&id_admin=<?print $id_admin;?> method=post>
        <?

            $strSQL1="SELECT * FROM admins WHERE id_admin='".$id_admin."'";			
            $result1=mysqli_query($connection, $strSQL1) or die("Не могу выполнить запрос2!");
            if($row=mysqli_fetch_array($result1))
			{
            ?>
                <div class="my-ddiv">
                                <div class="title111">
                                    <a href="info_admin.phtml?id_admin=<?print $row["id_admin"];?>">Вернуться к сотруднику</a>
                                </div>
                            <table class="tab-title">
                            <tr>
                                    <td class="td11">Карточка сотрудника</td>
                                    <td class="td11">
                                    <input class="but1" type="submit" value="Сохранить">                                    </td>
                            </tr>
                            </table>
                            <!-- <form class="my-form" action=cabinet.phtml?type=1 method=post> -->

							<table class="form-table">
								<tr>
									<td>
										<div class="input1">
											Фамилия:
										</div>
									</td>
									<td>
                                        <input class='input' name="fam" type="text" value="<?if ($mykey==1) Echo $_POST['fam'];else print $row["fam"];?>"></input>
                                    </td>
								</tr>
								<tr>
									<td>
										<div class="input1">
											Имя:
										</div>
									</td>
									<td>
                                        <input class='input' name="im" type="text" value="<?if ($mykey==1) Echo $_POST['im'];else print $row["im"];?>"></input>
                                    </td>
								</tr>
								<tr>
									<td>
										<div class="input1">
											Отчество:
										</div>
									</td>
									<td>
                                        <input class='input' name="otch" type="text" value="<?if ($mykey==1) Echo $_POST['otch'];else print $row["otch"];?>"></input>
									</td>
								</tr>

								<tr>
									<td>
										<div class="input1">
											Дата рождения:
										</div>
									</td>
									<td>
                                    <input class='input' name="birthday" type="date" value="<?if ($mykey==1) Echo $_POST['birthday'];else print $row["birthday"];?>"></input>
									</td>
								</tr>

								<tr>
									<td>
										<div class="input1">
											Должность:
										</div>
									</td>
									<td>
                                    <input class='input' name="position" type="text" value="<?if ($mykey==1) Echo $_POST['position'];else print $row["position"];?>"></input>
									</td>
								</tr>

								<tr>
									<td>
										<div class="input1">
											Почта:
										</div>
									</td>
									<td>
                                    <input class='input' name="mail" type="text" value="<?if ($mykey==1) Echo $_POST['mail'];else print $row["mail"];?>"></input>
									</td>
								</tr>

                                <tr>
									<td>
										<div class="input1">
											Телефон:
										</div>
									</td>
									<td>
                                    <input class='input' name="phone" type="text" value="<?if ($mykey==1) Echo $_POST['phone'];else print $row["phone"];?>"></input>
									</td>
								</tr>

                                <tr>
									<td>
										<div class="input1">
											Логин:
										</div>
									</td>
									<td>
                                    <input class='input' name="login" type="text" value="<?if ($mykey==1) Echo $_POST['login'];else print $row["login"];?>"></input>
									</td>
								</tr>

                                <tr>
									<td>
										<div class="input1">
											Пароль:
										</div>
									</td>
									<td>
                                    <input class='input' name="pass" type="text" value="<?if ($mykey==1) Echo $_POST['pass'];else print $row["pass"];?>"></input>
									</td>
								</tr>
							</table>

							<input type=hidden value=1 name=mykey>
                </div>
                <?	
            }
        ?>
        </form>
        <?
    }
?>

<?
if ($dostup==1)
    {
            $strSQL="SELECT * FROM admins  WHERE id_admin='".$id_admin."'";
            $result=mysqli_query($connection, $strSQL)or die("Не могу выполнить запрос!"); 
            if($row=mysqli_fetch_array($result))
            {
                if ($mykey==1){
                    if($orders!=""&$items_cats_themes!=""&$callbacks!=""&$customers!=""&$admins!="")
                    {
                        $strSQL1="UPDATE admins SET orders='".$orders."',items_cats_themes='".$items_cats_themes."',callbacks='".$callbacks."',customers='".$customers."',admins='".$admins."'  WHERE id_admin=".$id_admin;			
                        $result1=mysqli_query($connection, $strSQL1) or die("Не могу выполнить запрос!");	               
                        $message="<div class='mes2'><b>Доступ настроен успешно!</b> </div>";                 
                    }
                    else
                        $message="<div class='mes'><b>Настройте доступ для всех параметров!!</b> </div>"; 
                }
                    
            print $message;	
            }
        ?>


        <form class="my-form" action=edit_admin.phtml?dostup=1&id_admin=<?print $id_admin;?> method=post>
        <?

            $strSQL1="SELECT * FROM admins WHERE id_admin='".$id_admin."'";			
            $result1=mysqli_query($connection, $strSQL1) or die("Не могу выполнить запрос2!");
            if($row=mysqli_fetch_array($result1))
			{
            ?>
                <div class="my-ddiv">
                                <div class="title111">
                                    <a href="info_admin.phtml?id_admin=<?print $row["id_admin"];?>">Вернуться к сотруднику</a>
                                </div>
                            <table class="tab-title">
                            <tr>
                                    <td class="td11">Доступ сотрудника</td>
                                    <td class="td11">
                                    <input class="but1" type="submit" value="Сохранить">                                    </td>
                            </tr>
                            </table>
                            <!-- <form class="my-form" action=cabinet.phtml?type=1 method=post> -->

							<table class="form-table">
								<tr>
									<td>
										<div class="input1">
											ФИО:
										</div>
									</td>
									<td>
										<div class="input">
										&nbsp;<?print $row["fam"];?>  
											<?print $row["im"];?>  
											<?print $row["otch"];?> 
										</div>
									</td>
								</tr>
								<tr>
									<td>
										<div class="input1">
											Должность:
										</div>
									</td>
									<td>
										<div class="input">
										&nbsp;<?print $row["position"];?>  
										</div>
									</td>
								</tr>
								<tr>
									<td><br><br><br></td>
								</tr>
							</table>
							<div class="dostup">
				<table class="f">
								<tr>
									<td>
										<div class="i">
										&nbsp;Работа с заказами:
										</div>
									</td>
								</tr>
				</table>
				
				
				<div class="container">
					<div id="radios" >
						<label for="нет доступа к заказам" class="material-icons">
						<input type="radio" name="mode" id="нет доступа к заказам" value=0  <?if($row["orders"]==0){?>checked<?}?>/>
						<span><a><i class="fas fa-ban"></i></a></span>
						</label>                
						
						<label for="просмотр заказов" class="material-icons">
						<input type="radio" name="mode" id="просмотр заказов" value=1  <?if($row["orders"]==1){?>checked<?}?>/>
						<span><a><i class="fas fa-eye"></i></a></span>
						</label>
						
						<label for="изменение заказов" class="material-icons">
						<input type="radio" name="mode" id="изменение заказов" value=2 <?if($row["orders"]==2){?>checked<?}?>/>
						<span><a><i class="fas fa-feather"></i></a></span>
						</label>
					</div>
				</div>


				<table class="f">
								<tr>
									<td>
										<div class="i">
										&nbsp;Работа с товарами/категориями/тематиками:
										</div>
									</td>
								</tr>
				</table>
				
	
				<div class="container">
					<div id="radios">
						<label for="нет доступа к товарам" class="material-icons">
						<input type="radio" name="mode1" id="нет доступа к товарам" value=0 <?if($row["items_cats_themes"]==0){?>checked<?}?>/>
						<span><a><i class="fas fa-ban"></i></a></span>
						</label>                
						
						<label for="просмотр товаров" class="material-icons">
						<input  type="radio" name="mode1" id="просмотр товаров" value=1 <?if($row["items_cats_themes"]==1){?>checked<?}?>/>
						<span><a><i class="fas fa-eye"></i></a></span>
						</label>
						
						<label for="изменение товаров" class="material-icons">
						<input  type="radio" name="mode1" id="изменение товаров" value=2 <?if($row["items_cats_themes"]==2){?>checked<?}?>/>
						<span><a><i class="fas fa-feather"></i></a></span>
						</label>
					</div>
				</div>
				<table class="f">
								<tr>
									<td>
										<div class="i">
										&nbsp;Работа со звонками:
										</div>
									</td>
								</tr>
				</table>
	
				<div class="container">
					<div id="radios">
						<label for="нет доступа к звонкам" class="material-icons">
						<input type="radio" name="mode2" id="нет доступа к звонкам" value=0  <?if($row["callbacks"]==0){?>checked<?}?>/>
						<span><a><i class="fas fa-ban"></i></a></span>
						</label>                
						
						<label for="просмотр звонков" class="material-icons">
						<input  type="radio" name="mode2" id="просмотр звонков" value=1  <?if($row["callbacks"]==1){?>checked<?}?>/>
						<span><a><i class="fas fa-eye"></i></a></span>
						</label>
						
						<label for="изменение звонков" class="material-icons">
						<input  type="radio" name="mode2" id="изменение звонков" value=2  <?if($row["callbacks"]==2){?>checked<?}?>/>
						<span><a><i class="fas fa-feather"></i></a></span>
						</label>
					</div>
				</div>
				<table class="f">
								<tr>
									<td>
										<div class="i">
										&nbsp;Работа с покупателями:
										</div>
									</td>
								</tr>
				</table>
			
				<div class="container">
					<div id="radios">
						<label for="нет доступа к покупателям" class="material-icons">
						<input type="radio" name="mode3" id="нет доступа к покупателям" value=0  <?if($row["customers"]==0){?>checked<?}?>/>
						<span><a><i class="fas fa-ban"></i></a></span>
						</label>                
						
						<label for="просмотр покупателей" class="material-icons">
						<input  type="radio" name="mode3" id="просмотр покупателей" value=1  <?if($row["customers"]==1){?>checked<?}?>/>
						<span><a><i class="fas fa-eye"></i></a></span>
						</label>
						
						<label for="изменение покупателей" class="material-icons">
						<input  type="radio" name="mode3" id="изменение покупателей" value=2  <?if($row["customers"]==2){?>checked<?}?>/>
						<span><a><i class="fas fa-feather"></i></a></span>
						</label>
					</div>
				</div>
				<table class="f">
								<tr>
									<td>
										<div class="i">
										&nbsp;Работа с сотрудниками:
										</div>
									</td>
								</tr>
				</table>

				<div class="container">
					<div id="radios">
						<label for="нет доступа к сотрудникам" class="material-icons">
						<input type="radio" name="mode4" id="нет доступа к сотрудникам" value=0  <?if($row["admins"]==0){?>checked<?}?>/>
						<span><a><i class="fas fa-ban"></i></a></span>
						</label>                
						
						<label for="просмотр сотрудников" class="material-icons">
						<input  type="radio" name="mode4" id="просмотр сотрудников" value=1  <?if($row["admins"]==1){?>checked<?}?>/>
						<span><a><i class="fas fa-eye"></i></a></span>
						</label>
						
						<label for="изменение сотрудников" class="material-icons">
						<input  type="radio" name="mode4" id="изменение сотрудников" value=2  <?if($row["admins"]==2){?>checked<?}?>/>
						<span><a><i class="fas fa-feather"></i></a></span>
						</label>
					</div>
				</div>

				</div>
							<input type=hidden value=1 name=mykey>
							<input type=hidden value=1 name=dostup>
                </div>
                <?	
            }
        ?>
        </form>
        <?
    }
?>






<?
include("admin_footer.phtml");
?>
<?}}?>