<? $start = session_start();
$log = $_SESSION["log"];
if (!isset($log)) {
 include("authorization.phtml");
} else {
 $admins = $_SESSION["admins"];
 if ($admins == 0) { ?>Ошибка! У вас нет доступа к информации о сотруднике.<? } else {

                                                                         include("admin_header.phtml");
                                                                         //$start=session_start();
                                                                         ?>
<html>

<head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link href="css/info_admin.css" rel="stylesheet">
 <link src="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<?

                                                                        $title = "Карточка сотрудника";
                                                                         // $log=$_SESSION["log"];
                                                                         // $id=$_SESSION["id"];
                                                                         // $type=$_GET["type"];
                                                                         $mykey = $_POST["mykey"];
                                                                         $id_admin = $_GET["id_admin"];


                                                                         //$fam=$_POST["fam"];
                                                                         // $im=$_POST["im"];
                                                                         // $addr=$_POST["addr"];
                                                                         // $mail=$_POST["mail"];
                                                                         // $phone=$_POST["phone"];
                                                                         // $subscribe=$_POST["subscribe"];

                                                                         // if(!isset($log))
                                                                         // 	{
                                                                         // 		$success=false; 
                                                                         // 		$message="<div class='subtitlediv'><div class='subdiv'><div class='subtitle2'><b>Вы не авторизованы.</b></div></div></div>";              
                                                                         // 	}
                                                                         // else
                                                                         // 	$success=true;
                                                                         // print $message;
                                                                         // 
?>


<?
                                                                         // if($success)
                                                                         // 	
                                                                         include("admin_cabinet_nav.phtml");
                                                                         include("connect.phtml");
                                                                         $strSQL = "SELECT * FROM admins WHERE id_admin='" . $id_admin . "'";
                                                                         $result = mysqli_query($connection, $strSQL) or die("Не могу выполнить запрос!");
                                                                         if ($row = mysqli_fetch_array($result)) {
?>
<div class="my-ddiv">
  <!-- <div class="vl"></div>
<div class="tr"></div> -->
  <div>
   <div class="title1">
    <a href="admin_index.phtml?type=8">Вернуться к списку сотрудников</a>
   </div>
  </div>
  <table class="tab-title">
   <tr>
    <td class="td11"><? print $title ?></td>
    <? if ($admins == 2) { ?>
     <td class="td11">
      <div class="d-polosa"> <a href="edit_admin.phtml?card=1&id_admin=<? print $row["id_admin"]; ?>"><button class="but">Изменить</button></a></div>
     </td>
    <? } ?>
   </tr>
  </table>

  <?
                                                                          // 				if ($mykey==1){
                                                                          // 						if($fam!="" && $im!="" && $addr!="" && $mail!=""&& $phone != "")
                                                                          // 							{
                                                                          // 								$strSQL1="UPDATE customers SET fam='".$fam."', im='".$im."',addr='".$addr."', mail='".$mail."',  phone='".$phone."' WHERE id_customer=".$id;			
                                                                          // 								$result1=mysqli_query($connection, $strSQL1) or die("Не могу выполнить запрос!");
                                                                          // 								$_SESSION["log"]=$fam." ".$im;// обновили значение сеансовой переменной
                                                                          // 
  ?>

  <?
                                                                          // 								$message="<div class='mes2'><b>Изменение данных выполнено успешно!</b> </div>";                 
                                                                          // 							}
                                                                          // 						else
                                                                          // 						$message="<div class='mes'><b>Заполните все пустые поля!</b> </div>"; 

                                                                          // 					}
                                                                          // 					print $message;	
                                                                          // if ($type==1)
                                                                          // {

  ?>



  <!-- <form class="my-form" action=cabinet.phtml?type=1 method=post> -->

  <table class="form-table">
   <tr>
    <td>
     <div class="input1">
      ФИО:
     </div>
    </td>
    <td>
     <div class="input">
      &nbsp;<? print $row["fam"]; ?>
      <? print $row["im"]; ?>
      <? print $row["otch"]; ?>
     </div>
    </td>
   </tr>

   <tr>
    <td>
     <div class="input1">
      Дата рождения:
     </div>
    </td>
    <td>
     <div class="input">
      &nbsp;<? print $row["birthday"]; ?>
     </div>
    </td>
   </tr>

   <tr>
    <td>
     <div class="input1">
      Должность:
     </div>
    </td>
    <td>
     <div class="input">
      &nbsp;<? print $row["position"]; ?>
     </div>
    </td>
   </tr>

   <tr>
    <td>
     <div class="input1">
      Контакты:
     </div>
    </td>
    <td>
     <div class="input">
      &nbsp;<b>почта </b><? print $row["mail"]; ?>,<br>&nbsp;<b>тел. </b><? print $row["phone"]; ?>
     </div>
    </td>
   </tr>

   <tr>
    <td>
     <div class="input1">
      Аккаунт:
     </div>
    </td>
    <td>
     <div class="input">
      &nbsp;<b>логин </b><? print $row["login"]; ?>, <b>пароль </b><? print $row["pass"]; ?>
     </div>
    </td>
   </tr>
  </table>

  <input type=hidden value=1 name=mykey>

  <table class="tab-title">
   <tr>
    <td class="td11">Доступ сотрудника</td>
    <? if ($admins == 2) { ?>
     <td class="td11">
      <div class="d-polosa"> <a href="edit_admin.phtml?dostup=1&id_admin=<? print $row["id_admin"]; ?>"><button class="but">Изменить</button></a></div>
     </td>
    <? } ?>
   </tr>
  </table>

  <div class="dostup">

   <table class="f">
    <tr>
     <td>
      <div class="i">
       &nbsp;Работа с заказами:
      </div>
     </td>
    </tr>
   </table>


   <div class="container">
    <div id="radios">
     <label for="нет доступа" class="material-icons">
      <input type="radio" name="mode" id="нет доступа" value=0 disabled <? if ($row["orders"] == 0) { ?>checked<? } ?> />
      <span><a><i class="fas fa-ban"></i></a></span>
     </label>

     <label for="просмотр" class="material-icons">
      <input type="radio" name="mode" id="просмотр" value=1 disabled <? if ($row["orders"] == 1) { ?>checked<? } ?> />
      <span><a><i class="fas fa-eye"></i></a></span>
     </label>

     <label for="изменение" class="material-icons">
      <input type="radio" name="mode" id="изменение" value=2 disabled <? if ($row["orders"] == 2) { ?>checked<? } ?> />
      <span><a><i class="fas fa-feather"></i></a></span>
     </label>
    </div>
   </div>


   <table class="f">
    <tr>
     <td>
      <div class="i">
       &nbsp;Работа с товарами/категориями/тематиками:
      </div>
     </td>
    </tr>
   </table>

   <!-- <div class="block"></div> -->
   <div class="container">
    <div id="radios">
     <label for="нет доступа" class="material-icons">
      <input type="radio" name="mode1" id="нет доступа" value=0 disabled <? if ($row["items_cats_themes"] == 0) { ?>checked<? } ?> />
      <span><a><i class="fas fa-ban"></i></a></span>
     </label>

     <label for="просмотр" class="material-icons">
      <input type="radio" name="mode1" id="просмотр" value=1 disabled <? if ($row["items_cats_themes"] == 1) { ?>checked<? } ?> />
      <span><a><i class="fas fa-eye"></i></a></span>
     </label>

     <label for="изменение" class="material-icons">
      <input type="radio" name="mode1" id="изменение" value=2 disabled <? if ($row["items_cats_themes"] == 2) { ?>checked<? } ?> />
      <span><a><i class="fas fa-feather"></i></a></span>
     </label>
    </div>
   </div>
   <table class="f">
    <tr>
     <td>
      <div class="i">
       &nbsp;Работа со звонками:
      </div>
     </td>
    </tr>
   </table>
   <!-- <div class="block"></div> -->
   <div class="container">
    <div id="radios">
     <label for="нет доступа" class="material-icons">
      <input type="radio" name="mode2" id="нет доступа" value=0 disabled <? if ($row["callbacks"] == 0) { ?>checked<? } ?> />
      <span><a><i class="fas fa-ban"></i></a></span>
     </label>

     <label for="просмотр" class="material-icons">
      <input type="radio" name="mode2" id="просмотр" value=1 disabled <? if ($row["callbacks"] == 1) { ?>checked<? } ?> />
      <span><a><i class="fas fa-eye"></i></a></span>
     </label>

     <label for="изменение" class="material-icons">
      <input type="radio" name="mode2" id="изменение" value=2 disabled <? if ($row["callbacks"] == 2) { ?>checked<? } ?> />
      <span><a><i class="fas fa-feather"></i></a></span>
     </label>
    </div>
   </div>
   <table class="f">
    <tr>
     <td>
      <div class="i">
       &nbsp;Работа с покупателями:
      </div>
     </td>
    </tr>
   </table>
   <!-- <div class="block"></div> -->
   <div class="container">
    <div id="radios">
     <label for="нет доступа" class="material-icons">
      <input type="radio" name="mode3" id="нет доступа" value=0 disabled <? if ($row["customers"] == 0) { ?>checked<? } ?> />
      <span><a><i class="fas fa-ban"></i></a></span>
     </label>

     <label for="просмотрg" class="material-icons">
      <input type="radio" name="mode3" id="просмотр" value=1 disabled <? if ($row["customers"] == 1) { ?>checked<? } ?> />
      <span><a><i class="fas fa-eye"></i></a></span>
     </label>

     <label for="изменение" class="material-icons">
      <input type="radio" name="mode3" id="изменение" value=2 disabled <? if ($row["customers"] == 2) { ?>checked<? } ?> />
      <span><a><i class="fas fa-feather"></i></a></span>
     </label>
    </div>
   </div>
   <table class="f">
    <tr>
     <td>
      <div class="i">
       &nbsp;Работа с сотрудниками:
      </div>
     </td>
    </tr>
   </table>
   <!-- <div class="block"></div> -->
   <div class="container">
    <div id="radios">
     <label for="нет доступа" class="material-icons">
      <input type="radio" name="mode4" id="нет доступа" value=0 disabled <? if ($row["admins"] == 0) { ?>checked<? } ?> />
      <span><a><i class="fas fa-ban"></i></a></span>
     </label>

     <label for="просмотр" class="material-icons">
      <input type="radio" name="mode4" id="просмотр" value=1 disabled <? if ($row["admins"] == 1) { ?>checked<? } ?> />
      <span><a><i class="fas fa-eye"></i></a></span>
     </label>

     <label for="изменение" class="material-icons">
      <input type="radio" name="mode4" id="изменение" value=2 disabled <? if ($row["admins"] == 2) { ?>checked<? } ?> />
      <span><a><i class="fas fa-feather"></i></a></span>
     </label>
    </div>
   </div>

  </div>




  <!-- </form> -->
 </div>
<?

}
     // }
?>

<?


// mysqli_close($connection);				
  // 		}
?>

</html>
<?
    include("admin_footer.phtml");
?>
<? }
} ?>
