<?$start=session_start();
$log=$_SESSION["log"];
if(!isset($log)){include("authorization.phtml");} else{
    $items_cats_themes=$_SESSION["items_cats_themes"];
    if($items_cats_themes==0){?>Ошибка! У вас нет доступа к просмотру категорий и тем.<?} else{

include("admin_header.phtml");
include("connect.phtml");?>
<html>
<head>
<link href="css/edit_cat_theme.css" rel="stylesheet">
</head>


<?
$id_cat = $_GET["id_cat"];
$id_theme = $_GET["id_theme"];
$cat = $_GET["cat"];
$theme = $_GET["theme"];

$title1="Товаров данной категории - ";
$title2="Товаров данной тематики - ";
    include("admin_cabinet_nav.phtml");   
?>

<?

    if ($cat==1){
            $str="SELECT * FROM items WHERE id_cat='".$id_cat."'";			
            $res1=mysqli_query($connection, $str) or die("Не могу выполнить запрос2!");
            $allkolvo_cat=0; 
            while($row=mysqli_fetch_array($res1))
            {
                $allkolvo_cat=$allkolvo_cat+1;
            }

            $strSQL1="SELECT * FROM categories WHERE id_cat='".$id_cat."'";			
            $result1=mysqli_query($connection, $strSQL1) or die("Не могу выполнить запрос2!");
            ?>
            <div class="shopping-cart">
                <div>
                    <div class="title1">
                    <a href="admin_index.phtml?type=6">Вернуться к списку категорий и тем</a>
                    </div>
                </div>
                <div>
                    <div class="title">
                    <?print $title1;?>&nbsp;<?print $allkolvo_cat;?>&nbsp; шт
                    </div>
                </div>
                <? 
                while($row=mysqli_fetch_array($result1))
                {
                    ?>
                    <div class="item">
                        <div class="description">
                            <span1>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#727272">№&nbsp;<?print $row["id_cat"];?></font></b>&nbsp;&nbsp;
                                <div class='input-line-h4'><?print $row["name_cat"];?></div>
                            </span1>
                            <br><br><br><br>
                            <b><font color="#727272">Товары данной категории:</font></b>
                            <br>
                            <span2>
                                <? 
                                $stri="SELECT * FROM items WHERE id_cat='".$id_cat."'";			
                                $res1i=mysqli_query($connection, $stri) or die("Не могу выполнить запрос2!");
                                while($rowi=mysqli_fetch_array($res1i))
                                {
                                ?>
                                <div class="pun">
                                    <div class="image">
                                    <a href="edit_item.phtml?id_item=<?print $rowi["id_item"];?>"><img width="100%" src="<?print $rowi["image"];?>" alt="" /></a>
                                    </div>
                                    <?print $rowi["name_item"];?>
                                </div>
                                <?  
                                }?>
                            </span2>
                        </div>     
                        
                    </div>
                <?
                }
                ?> 
            </div>
        <?
        }
        ?>



<?

    if ($theme==1){
            $str1="SELECT * FROM items WHERE id_theme='".$id_theme."'";			
            $res2=mysqli_query($connection, $str1) or die("Не могу выполнить запрос2!");
            $allkolvo_theme=0; 
            while($row1=mysqli_fetch_array($res2))
            {
                $allkolvo_theme=$allkolvo_theme+1;
            }

            $strSQL2="SELECT * FROM themes WHERE id_theme='".$id_theme."'";			
            $result2=mysqli_query($connection, $strSQL2) or die("Не могу выполнить запрос2!");
            ?>
            <div class="shopping-cart">
                <div>
                    <div class="title1">
                    <a href="admin_index.phtml?type=6">Вернуться к списку категорий и тем</a>
                    </div>
                </div>
                <div>
                    <div class="title">
                    <?print $title2;?>&nbsp;<?print $allkolvo_theme;?>&nbsp; шт
                    </div>
                </div>
                <? 
                while($row2=mysqli_fetch_array($result2))
                {
                    ?>
                    <div class="item">
                        <div class="description">
                            <span1>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#727272">№&nbsp;<?print $row2["id_theme"];?></font></b>&nbsp;&nbsp;
                                <div class='input-line-h4'><?print $row2["name_theme"];?></div>
                            </span1>
                            <br><br><br><br>
                            <b><font color="#727272">Товары данной тематики:</font></b>
                            <br>
                            <span2>
                                <? 
                                $stri="SELECT * FROM items WHERE id_theme='".$id_theme."'";			
                                $res2i=mysqli_query($connection, $stri) or die("Не могу выполнить запрос2!");
                                while($row2i=mysqli_fetch_array($res2i))
                                {
                                ?>
                                <div class="pun">
                                    <div class="image">
                                    <a href="edit_item.phtml?id_item=<?print $row2i["id_item"];?>"><img width="100%" src="<?print $row2i["image"];?>" alt="" /></a>
                                    </div>
                                    <?print $row2i["name_item"];?>
                                </div>
                                <?  
                                }?>
                            </span2>
                        </div>     
                        
                    </div>
                <?
                }
                ?> 
            </div>
        <?
        }
        ?>
<?
include("admin_footer.phtml");
?>
<?}}?>
